### ISSUE TITLE
Maintenance?

### ISSUE THREAD

**Issue by michaeloa** [sdarwin/Ansible-Phabricator#1]
Hi. Is this project still being maintained? Ran this on Ubuntu 18.04 this week, and identified a couple of issues + one of the recent phabricator upgrades from 2019 breaks this playbook (and presumably all the others on galaxy as well) due to changes in the config API.

**Comment by sdarwin** [comment]
Hi Michael, you are welcome to submit pull requests. If Ubuntu 18 or Phabricator has changed, and now the playbook is broken, we should fix it. (ideally still maintaining backwards compatibility with the previous versions too)

**Comment by michaeloa** [comment]
Sure. The change that breaks the playbook is detailed here: https://secure.phabricator.com/w/changelog/2019.01/

A bunch of configurations have been removed, among them metamta configs used by the playbook.

I mainly just side-stepped the issues, but I'll try to see if I can make the time to create a clean fix sometime in the next couple of weeks but I'm mostly just doing some prototyping with terraform/ansible, so don't know how much time I'll have for this.

**Comment by sdarwin** [comment]
@michaeloa, the role has been updated to fix metamta, please try it out if you have a chance.

**Comment by michaeloa** [comment]
Reinstalled a server today using ansible-galaxy to pull down the latest version. Haven't set it up with e-mail or anything, so can't guarantee it's working 100%, but the playbook runs now. Thanks.
